### ISSUE TITLE
Megasync build failed

### ISSUE THREAD

**Issue by HougeLangley** [amedeos/amedeos-overlay#1]
>>> Emerging (9 of 9) net-misc/megasync-4.3.3::amedeos
>>> Unpacking source...
 * Repository id: meganz_MEGAsync.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_MEGANZ_MEGASYNC
 *   EGIT_OVERRIDE_BRANCH_MEGANZ_MEGASYNC
 *   EGIT_OVERRIDE_COMMIT_MEGANZ_MEGASYNC
 *   EGIT_OVERRIDE_COMMIT_DATE_MEGANZ_MEGASYNC
 * 
 * Fetching https://github.com/meganz/MEGAsync ...
git fetch https://github.com/meganz/MEGAsync +refs/tags/v4.3.3.0_Linux:refs/tags/v4.3.3.0_Linux
git symbolic-ref refs/git-r3/net-misc/megasync/0/__main__ refs/tags/v4.3.3.0_Linux
 * Using submodule src/MEGASync/mega
 * Repository id: meganz_sdk.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_MEGANZ_SDK
 *   EGIT_OVERRIDE_BRANCH_MEGANZ_SDK
 *   EGIT_OVERRIDE_COMMIT_MEGANZ_SDK
 *   EGIT_OVERRIDE_COMMIT_DATE_MEGANZ_SDK
 * 
 * Fetching https://github.com/meganz/sdk.git ...
git fetch https://github.com/meganz/sdk.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/net-misc/megasync/0/src_MEGASync_mega/__main__ b2948c7c77862e99dee912f4fe321d3c6dac6b09
 * Checking out https://github.com/meganz/MEGAsync to /var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3 ...
git checkout --quiet refs/tags/v4.3.3.0_Linux
GIT update -->
   repository:               https://github.com/meganz/MEGAsync
   at the commit:            cc421b937e0b69d034f679a3ee4f5dab0acbb7f8
 * Using submodule src/MEGASync/mega
 * Checking out https://github.com/meganz/sdk.git to /var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/mega ...
git checkout --quiet b2948c7c77862e99dee912f4fe321d3c6dac6b09
GIT update -->
   repository:               https://github.com/meganz/sdk.git
   at the commit:            b2948c7c77862e99dee912f4fe321d3c6dac6b09
>>> Source unpacked in /var/tmp/portage/net-misc/megasync-4.3.3/work
>>> Preparing source in /var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3 ...
 * Running eautoreconf in '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/mega' ...
 * Running libtoolize --install --copy --force --automake ...                                    [ ok ]
 * Running aclocal -I m4 ...                                                                     [ ok ]
 * Running autoconf --force ...                                                                  [ ok ]
 * Running autoheader ...                                                                        [ ok ]
 * Running automake --add-missing --copy --foreign --force-missing ...                           [ ok ]
 * Running elibtoolize in: megasync-4.3.3/src/MEGASync/mega/
 *   Applying portage/1.2.0 patch ...
 *   Applying sed/1.5.6 patch ...
 *   Applying as-needed/2.4.3 patch ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3 ...
 * econf: updating megasync-4.3.3/src/MEGASync/mega/config.sub with /usr/share/gnuconfig/config.sub
 * econf: updating megasync-4.3.3/src/MEGASync/mega/config.guess with /usr/share/gnuconfig/config.guess
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/megasync-4.3.3 --htmldir=/usr/share/doc/megasync-4.3.3/html --with-sysroot=/ --libdir=/usr/lib64 --disable-silent-rules --disable-curl-checks --disable-megaapi --with-zlib --with-sqlite --with-cryptopp --with-cares --with-curl --without-termcap --disable-posix-threads --with-sodium --without-freeimage --with-readline --disable-examples --disable-java --disable-php --disable-python --enable-chat --enable-gcc-hardening
checking for x86_64-pc-linux-gnu-gcc... x86_64-pc-linux-gnu-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-pc-linux-gnu-gcc accepts -g... yes
checking for x86_64-pc-linux-gnu-gcc option to accept ISO C89... none needed
checking whether x86_64-pc-linux-gnu-gcc understands -c and -o together... yes
checking how to run the C preprocessor... x86_64-pc-linux-gnu-gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /usr/lib/portage/python3.7/ebuild-helpers/xattr/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of x86_64-pc-linux-gnu-gcc... none
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by x86_64-pc-linux-gnu-gcc... /usr/x86_64-pc-linux-gnu/bin/ld
checking if the linker (/usr/x86_64-pc-linux-gnu/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/x86_64-pc-linux-gnu-nm -B
checking the name lister (/usr/bin/x86_64-pc-linux-gnu-nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-pc-linux-gnu/bin/ld option to reload object files... -r
checking for x86_64-pc-linux-gnu-objdump... x86_64-pc-linux-gnu-objdump
checking how to recognize dependent libraries... pass_all
checking for x86_64-pc-linux-gnu-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for x86_64-pc-linux-gnu-ar... x86_64-pc-linux-gnu-ar
checking for archiver @FILE support... @
checking for x86_64-pc-linux-gnu-strip... x86_64-pc-linux-gnu-strip
checking for x86_64-pc-linux-gnu-ranlib... x86_64-pc-linux-gnu-ranlib
checking command to parse /usr/bin/x86_64-pc-linux-gnu-nm -B output from x86_64-pc-linux-gnu-gcc object... ok
checking for sysroot... /
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for x86_64-pc-linux-gnu-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if x86_64-pc-linux-gnu-gcc supports -fno-rtti -fno-exceptions... no
checking for x86_64-pc-linux-gnu-gcc option to produce PIC... -fPIC -DPIC
checking if x86_64-pc-linux-gnu-gcc PIC flag -fPIC -DPIC works... yes
checking if x86_64-pc-linux-gnu-gcc static flag -static works... yes
checking if x86_64-pc-linux-gnu-gcc supports -c -o file.o... yes
checking if x86_64-pc-linux-gnu-gcc supports -c -o file.o... (cached) yes
checking whether the x86_64-pc-linux-gnu-gcc linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether make supports nested variables... (cached) yes
checking for size_t... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for pid_t... yes
checking for off_t... yes
checking for ssize_t... yes
checking for x86_64-pc-linux-gnu-g++... x86_64-pc-linux-gnu-g++
checking whether we are using the GNU Objective C++ compiler... no
checking whether x86_64-pc-linux-gnu-g++ accepts -g... no
checking dependency style of x86_64-pc-linux-gnu-g++... none
checking for x86_64-pc-linux-gnu-g++... x86_64-pc-linux-gnu-g++
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-pc-linux-gnu-g++ accepts -g... yes
checking dependency style of x86_64-pc-linux-gnu-g++... none
checking how to run the C++ preprocessor... x86_64-pc-linux-gnu-g++ -E
checking for ld used by x86_64-pc-linux-gnu-g++... /usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64
checking if the linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the x86_64-pc-linux-gnu-g++ linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for x86_64-pc-linux-gnu-g++ option to produce PIC... -fPIC -DPIC
checking if x86_64-pc-linux-gnu-g++ PIC flag -fPIC -DPIC works... yes
checking if x86_64-pc-linux-gnu-g++ static flag -static works... yes
checking if x86_64-pc-linux-gnu-g++ supports -c -o file.o... yes
checking if x86_64-pc-linux-gnu-g++ supports -c -o file.o... (cached) yes
checking whether the x86_64-pc-linux-gnu-g++ linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether build environment is sane... yes
checking for cppcheck... no
checking whether x86_64-pc-linux-gnu-g++ supports C++11 features by default... yes
checking for ANSI C header files... (cached) yes
checking for ANSI C header files... (cached) yes
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for _LARGEFILE_SOURCE value needed for large files... no
checking for off_t... (cached) yes
checking size of uint64_t... 8
checking whether struct tm is in sys/time.h or time.h... time.h
checking for off_t... (cached) yes
checking for size_t... (cached) yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/timeb.h usability... yes
checking sys/timeb.h presence... yes
checking for sys/timeb.h... yes
checking htonl usability... no
checking htonl presence... no
checking for htonl... no
checking glob.h usability... yes
checking glob.h presence... yes
checking for glob.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking sys/malloc.h usability... no
checking sys/malloc.h presence... no
checking for sys/malloc.h... no
checking malloc/malloc.h usability... no
checking malloc/malloc.h presence... no
checking for malloc/malloc.h... no
checking whether C++ compiler accepts -fPIC... yes
checking whether the linker accepts -fPIC... yes
checking for dlopen in -ldl... yes
checking sys/inotify.h usability... yes
checking sys/inotify.h presence... yes
checking for sys/inotify.h... yes
checking mcheck.h usability... yes
checking mcheck.h presence... yes
checking for mcheck.h... yes
checking for inotify_init1... yes
checking for fdopendir... yes
checking for select... yes
checking for sendfile in -lsendfile... no
checking for socket in -lsocket... no
checking for clock_gettime in -lrt... yes
checking platform options... no
checking whether C++ compiler accepts -fstack-protector-all... yes
checking whether the linker accepts -fstack-protector-all... yes
checking if building Java bindings... yes
checking for libcryptopp... checking cryptopp/cryptlib.h usability... yes
checking cryptopp/cryptlib.h presence... yes
checking for cryptopp/cryptlib.h... yes
checking for main in -lcryptopp... yes
checking for libsodium... checking sodium.h usability... yes
checking sodium.h presence... yes
checking for sodium.h... yes
checking for sodium_init in -lsodium... yes
checking for libpcrecpp... checking for libraw... checking libraw/libraw.h usability... yes
checking libraw/libraw.h presence... yes
checking for libraw/libraw.h... yes
checking for libraw_init in -lraw... yes
checking for libuv... --with-libuv not specified
checking uv.h usability... yes
checking uv.h presence... yes
checking for uv.h... yes
checking for uv_run in -luv... yes
checking for zlib... checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for main in -lz... yes
checking for SQLite... yes
checking sqlite3.h usability... yes
checking sqlite3.h presence... yes
checking for sqlite3.h... yes
checking for sqlite3_open in -lsqlite3... yes
checking for Berkeley DB... --with-db not specified
checking for ffmpeg... --with-ffmpeg not specified
checking ffmpeg-mega/libavutil/macros.h usability... no
checking ffmpeg-mega/libavutil/macros.h presence... no
checking for ffmpeg-mega/libavutil/macros.h... no
checking libavutil/macros.h usability... yes
checking libavutil/macros.h presence... yes
checking for libavutil/macros.h... yes
checking for main in -lavformat... yes
checking for libzen... --with-libzen not specified
checking ZenLib/Ztring.h usability... yes
checking ZenLib/Ztring.h presence... yes
checking for ZenLib/Ztring.h... yes
checking for _ZN6ZenLib15int8u2BigEndianEPch in -lzen... yes
checking for pthread_create in -lpthread... yes
checking for libmediainfo... --with-libmediainfo not specified
checking MediaInfo/MediaInfo.h usability... yes
checking MediaInfo/MediaInfo.h presence... yes
checking for MediaInfo/MediaInfo.h... yes
checking for MediaInfo_Info_Version in -lmediainfo... yes
libmediainfo worked worked with -DUNICODE
checking for aio_write in -lrt... yes
checking for OpenSSL... --with-openssl not specified
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for SSL_new in -lssl... yes
checking for c-ares... checking ares.h usability... yes
checking ares.h presence... yes
checking for ares.h... yes
checking for ares_library_init in -lcares... yes
checking curl/curl.h usability... yes
checking curl/curl.h presence... yes
checking for curl/curl.h... yes
checking for main in -lcurl... yes
configure: skipping cURL checks.
checking if building example applications... no
checking for FreeImage... no
checking if building tests... no
checking if building Python bindings... no
checking if building PHP bindings... yes
checking for main in -lstdc++fs... yes
checking for x86_64-pc-linux-gnu-doxygen... no
checking for doxygen... /usr/bin/doxygen
checking for x86_64-pc-linux-gnu-perl... no
checking for perl... /usr/bin/perl
checking for x86_64-pc-linux-gnu-latex... no
checking for latex... no
configure: WARNING: latex not found - will not generate doxygen PostScript documentation
checking for x86_64-pc-linux-gnu-makeindex... no
checking for makeindex... no
checking for x86_64-pc-linux-gnu-dvips... no
checking for dvips... no
checking for x86_64-pc-linux-gnu-egrep... no
checking for egrep... /bin/egrep
checking for x86_64-pc-linux-gnu-pdflatex... no
checking for pdflatex... no
configure: WARNING: pdflatex not found - will not generate doxygen PDF documentation
checking for x86_64-pc-linux-gnu-makeindex... no
checking for makeindex... no
checking for x86_64-pc-linux-gnu-egrep... /bin/egrep
checking that generated files are newer than configure... done
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating libmega.pc
config.status: creating doc/Doxyfile
config.status: creating include/mega/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure: Configured to build Mega SDK:

  SDK version:      3.7.0
  Host setup:       x86_64-pc-linux-gnu
  Install prefix:   /usr
  Compiler:         x86_64-pc-linux-gnu-g++
  CXXFLAGS:         -march=native -O2 -pipe -DNDEBUG=1 -fPIC -D_FORTIFY_SOURCE=2 -fstack-protector-all
  LDFLAGS:          -lstdc++fs -lrt -Wl,-O1 -Wl,--as-needed
  gcc hardening:    yes
  debug:            no
  static:           no
  sync subsystem:   yes
  chat:             yes
  MEGA API          no
  example apps:     no

  inotify:          yes
  posix threads:    no

  Python bindings:  no
  Python3 bindings: no
  PHP bindings:     no
  SWIG_FLAGS_PHP:   

  Java bindings:    no

  OpenSSL:            -lssl -lcrypto
  Crypto++:           -lcryptopp
  Sodium:             -lsodium
  Zlib:               -lz
  SQLite3:            -lsqlite3
  c-ares:             -lcares
  cURL:              -lcurl
  FreeImage:          
  Readline:           
  Termcap:            
  PCRE:               
  LIBUV:              -luv
  LIBRAW:              -lraw -fopenmp
  LIBMEDIAINFO:       -DUNICODE -lmediainfo -lzen
  FFMPEG:             -lavcodec -lavformat -lavutil -lswscale

 * Running qmake ...
Info: creating stash file /var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/.qmak [ ok ]
WARNING: Project ERROR: Unknown module(s) in QT: x11extras macextras winextras
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_ar.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_de.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_en.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_es.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_fr.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_id.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_it.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_ja.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_ko.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_nl.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_pl.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_pt_BR.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_pt.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_ro.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_ru.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_th.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_tl.qm'...
    Generated 789 translation(s) (258 finished and 531 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_uk.qm'...
    Generated 709 translation(s) (260 finished and 449 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_vi.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_zh_CN.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
Updating '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/gui/translations/MEGASyncStrings_zh_TW.qm'...
    Generated 849 translation(s) (257 finished and 592 unfinished)
>>> Source configured.
>>> Compiling source in /var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3 ...
make -j12 -C src INSTALL_ROOT=/var/tmp/portage/net-misc/megasync-4.3.3/image 
make: Entering directory '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src'
cd MEGASync/ && ( test -e Makefile || /usr/lib64/qt5/bin/qmake -o Makefile /var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/MEGASync.pro 'QMAKE_AR=x86_64-pc-linux-gnu-ar cqs' QMAKE_CC=x86_64-pc-linux-gnu-gcc QMAKE_LINK_C=x86_64-pc-linux-gnu-gcc QMAKE_LINK_C_SHLIB=x86_64-pc-linux-gnu-gcc QMAKE_CXX=x86_64-pc-linux-gnu-g++ QMAKE_LINK=x86_64-pc-linux-gnu-g++ QMAKE_LINK_SHLIB=x86_64-pc-linux-gnu-g++ QMAKE_OBJCOPY=x86_64-pc-linux-gnu-objcopy QMAKE_RANLIB= QMAKE_STRIP= 'QMAKE_CFLAGS=-march=native -O2 -pipe' QMAKE_CFLAGS_RELEASE= QMAKE_CFLAGS_DEBUG= 'QMAKE_CXXFLAGS=-march=native -O2 -pipe' QMAKE_CXXFLAGS_RELEASE= QMAKE_CXXFLAGS_DEBUG= 'QMAKE_LFLAGS=-Wl,-O1 -Wl,--as-needed' QMAKE_LFLAGS_RELEASE= QMAKE_LFLAGS_DEBUG= CONFIG+=release ) && make -f Makefile 
Project MESSAGE: THIRDPARTY_VCPKG_BASE_PATH: /var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src/MEGASync/../../../3rdParty
Project MESSAGE: VCPKG_TRIPLET: x64-linux
Project MESSAGE: vcpkg not used
Project MESSAGE: Installing desktop files.
Project ERROR: Unknown module(s) in QT: x11extras
make: *** [Makefile:47: sub-MEGASync-make_first] Error 3
make: Leaving directory '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3/src'
 * ERROR: net-misc/megasync-4.3.3::amedeos failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=net-misc/megasync-4.3.3::amedeos'`,
 * the complete build log and the output of `emerge -pqv '=net-misc/megasync-4.3.3::amedeos'`.
 * The complete build log is located at '/var/tmp/portage/net-misc/megasync-4.3.3/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-misc/megasync-4.3.3/temp/environment'.
 * Working directory: '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3'
 * S: '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3'

>>> Failed to emerge net-misc/megasync-4.3.3, Log file:

>>>  '/var/tmp/portage/net-misc/megasync-4.3.3/temp/build.log'

 * Messages for package net-misc/megasync-4.3.3:

 * ERROR: net-misc/megasync-4.3.3::amedeos failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=net-misc/megasync-4.3.3::amedeos'`,
 * the complete build log and the output of `emerge -pqv '=net-misc/megasync-4.3.3::amedeos'`.
 * The complete build log is located at '/var/tmp/portage/net-misc/megasync-4.3.3/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-misc/megasync-4.3.3/temp/environment'.
 * Working directory: '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3'
 * S: '/var/tmp/portage/net-misc/megasync-4.3.3/work/megasync-4.3.3'
 * 
 * The following package has failed to build, install, or execute postinst:
 * 
 *  (net-misc/megasync-4.3.3:0/0::amedeos, ebuild scheduled for merge), Log file:
 *   '/var/tmp/portage/net-misc/megasync-4.3.3/temp/build.log'
 *

**Comment by amedeos** [comment]
I added dev-qt/qtx11extras depency

**Comment by HougeLangley** [comment]
Rebuild, no luck. the full log
[megasync_build_failed.log](https://github.com/amedeos/amedeos-overlay/files/5097580/megasync_build_failed.log)
 attachment
